name: build
on:
  push:
  pull_request:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build containers
        run: |
          docker compose -f compose.e2etest.yml build
          docker compose -f compose.e2etest.yml pull
      - name: Start containers
        uses: JarvusInnovations/background-action@v1
        with:
          run: |
            docker compose -f compose.e2etest.yml up &
          wait-on: |
            tcp:127.0.0.1:3000
            tcp:127.0.0.1:5000
          log-output-if: true
      - name: Push demo image to registry
        run: |
          docker image inspect -f '{{.Id}}' buildpack-deps:bullseye | tee ~/push-image-id
          docker image tag buildpack-deps:bullseye localhost:5000/demo
          docker image push localhost:5000/demo
          docker image rm -f $(cat ~/push-image-id)
      - name: Pull demo image over NDN
        run: |
          docker image pull localhost:3000/demo
          docker image inspect -f '{{.Id}}' localhost:3000/demo | tee ~/pull-image-id
          diff ~/push-image-id ~/pull-image-id
      - name: Check code style
        run: |
          corepack pnpm install
          corepack pnpm typecheck
          corepack pnpm lint
          go fmt ./...
          go vet ./...
          git diff --exit-code
    timeout-minutes: 30
