name: build
on:
  push:
  pull_request:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Start containers
        run: |
          docker compose -f compose.test.yml build
          docker compose -f compose.test.yml pull
          docker compose -f compose.test.yml up -d
          sleep 5
      - name: Push demo image to registry
        run: |
          docker image inspect -f '{{.Id}}' $DEMO_IMAGE || docker pull $DEMO_IMAGE
          docker image inspect -f '{{.Id}}' $DEMO_IMAGE | tee ~/push-image-id
          docker image tag $DEMO_IMAGE localhost:5000/demo
          docker image push localhost:5000/demo
          docker image rm -f $(cat ~/push-image-id)
        env:
          DEMO_IMAGE: node:20
      - name: Pull demo image over NDN
        run: |
          docker image pull localhost:3000/demo
          docker image inspect -f '{{.Id}}' localhost:3000/demo | tee ~/pull-image-id
          diff ~/push-image-id ~/pull-image-id
      - name: Gather container logs
        if: ${{ !cancelled() }}
        run: |
          for SERVICE in nfd server client; do
            echo
            echo $SERVICE
            docker compose -f compose.test.yml logs --no-log-prefix $SERVICE
          done
      - name: Check code style
        run: |
          corepack pnpm install
          corepack pnpm typecheck
          corepack pnpm lint
          go fmt ./...
          go vet ./...
          git diff --exit-code
    timeout-minutes: 30
